apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
      targetPort: 50051
    - name: metrics
      protocol: TCP
      port: 2225
      targetPort: 2223
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-d
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
            - configMapRef:
                name: auth-env
          image: krixlion/dev_forum-auth:0.1.0
          imagePullPolicy: IfNotPresent
          name: server
          ports:
            - name: grpc
              containerPort: 50051
            - name: metrics
              containerPort: 2223
          resources:
            limits:
              cpu: 20m
              memory: 150Mi
            requests:
              cpu: 5m
              memory: 80Mi
          volumeMounts:
            - name: tls-certs
              mountPath: /tls
              readOnly: true
            - name: tls-client-certs
              mountPath: /tls/client
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-secret-auth
        - name: tls-client-certs
          secret:
            secretName: tls-secret-auth-client-user
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate-auth
spec:
  secretName: tls-secret-auth
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - key encipherment
    - digital signature
  dnsNames:
    - "auth-service"
  issuerRef:
    name: root-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate-auth-client-user
spec:
  secretName: tls-secret-auth-client-user
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - client auth
    - key encipherment
    - digital signature
  dnsNames:
    - "auth-service"
  issuerRef:
    name: root-issuer
    kind: Issuer
