apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: grpc
      protocol: TCP
      port: 50053
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-d
spec:
  selector:
    matchLabels:
      app: auth
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth
    spec:
      restartPolicy: Always
      containers:
        - envFrom:
            - configMapRef:
                name: auth-env
          image: krixlion/dev_forum-auth:0.1.0
          imagePullPolicy: IfNotPresent
          name: server
          args: []
          ports:
            - name: grpc
              containerPort: 50051
          resources:
            limits:
              cpu: 20m
              memory: 150Mi
            requests:
              cpu: 5m
              memory: 80Mi
          volumeMounts: []
      volumes: []
