apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-cluster
spec:
  serviceName: vault-service
  replicas: 1
  selector:
    matchLabels:
      database: vault
  volumeClaimTemplates:
    - metadata:
        name: vault-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 300Mi
  template:
    metadata:
      labels:
        database: vault
    spec:
      containers:
        - name: vault-cluster
          image: hashicorp/vault:1.13
          env: []
          ports:
            - name: vault
              containerPort: 8200
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 250Mi
            requests:
              cpu: 150m
              memory: 50Mi
          volumeMounts:
            - name: vault-data
              mountPath: /vault/file
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
spec:
  selector:
    database: vault
  clusterIP: None
  ports:
    - port: 8200
      targetPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: vault-service-ui
spec:
  type: LoadBalancer
  selector:
    database: vault
    statefulset.kubernetes.io/pod-name: vault-cluster-0
  ports:
    - name: http
      port: 8200
      targetPort: 8200
