apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate-auth-client
spec:
  secretName: tls-secret-auth-client
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - client auth
    - key encipherment
    - digital signature
  dnsNames:
    - "auth-service"
  issuerRef:
    name: root-issuer
    kind: Issuer
