- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: tls-certs
    secret:
      secretName: tls-secret-auth

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: tls-certs
    mountPath: /tls
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: tls-client-certs
    secret:
      secretName: tls-secret-auth-client

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: tls-client-certs
    mountPath: /tls/client
    readOnly: true
