apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate-auth
spec:
  secretName: tls-secret-auth
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - key encipherment
    - digital signature
  dnsNames:
    - "auth-service"
  issuerRef:
    name: root-issuer
    kind: Issuer
