resources:
  - ../../base
  - server-cert.yaml
  - user-client-cert.yaml

patches:
  - path: deployment-patches.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: auth-d
