# Add a volume mounted to local codebase for instant hot reload.
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: hot-reload
    persistentVolumeClaim:
      claimName: hot-reload-pvc-auth

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: hot-reload
    mountPath: /app

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: tls-certs
    secret:
      secretName: tls-secret-auth

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: tls-certs
    mountPath: /tls
    readOnly: true

- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: tls-client-certs
    secret:
      secretName: tls-secret-auth-client-user

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: tls-client-certs
    mountPath: /tls/client
    readOnly: true

- op: replace
  path: /spec/template/spec/containers/0/name
  value: "debug"

- op: add
  path: /spec/template/spec/containers/0/ports/-
  value:
    name: delve
    containerPort: 2345

- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      cpu: 2000m
      memory: 750Mi
    requests:
      cpu: 500m
      memory: 250Mi
