resources:
  - dev-volume.yaml
  - ../tls

namespace: dev

replicas:
  - name: auth-d
    count: 1

images:
  - name: krixlion/dev_forum-auth
    newName: krixlion/go-reflex-dlv
    newTag: latest

patches:
  - path: deployment-patches.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: auth-d

  - path: service-patches.yaml
    target:
      version: v1
      kind: Service
      name: auth-service

  - path: vault-patches.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: vault-cluster

configMapGenerator:
  - name: auth-env
    env: auth.properties
